// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykpkpvxwuzljplmvcweh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrcGtwdnh3dXpsanBsbXZjd2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDUzNzEsImV4cCI6MjA1NDE4MTM3MX0.TT7Z9BdpoxLcy1RGfJ5x5KxWGMaq1KP2WKLy6lZmmAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);